name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4

      - name: Xcode version
        run: xcodebuild -version

      - name: Resolve packages
        run: xcodebuild -resolvePackageDependencies -project AirBattery.xcodeproj -scheme AirBattery

      - name: Build
        run: >
          xcodebuild
          -project AirBattery.xcodeproj
          -scheme AirBattery
          -configuration Debug
          -destination 'platform=macOS'
          CODE_SIGNING_ALLOWED=NO
          build
